name: Fontship

on: [push, pull_request]

jobs:

  fontship:
    name: Fontship
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: |
          git fetch --prune --tags ||:
      - name: Fontship make
        id: fontship
        uses: theleagueof/fontship@v0
        with:
          args: make dist
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.fontship.outputs.DISTDIR }}
          path: ${{ steps.fontship.outputs.DISTDIR }}.zip
      - name: FontProof
        id: fontproof
        uses: docker://siletypesetter/fontproof:latest
        with:
          args: proofs/waterfalls.sil
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: waterfalls
          path: proofs/waterfalls.pdf
      - name: Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ steps.fontship.outputs.DISTDIR }}.zip
            ${{ steps.fontship.outputs.DISTDIR }}.tar.zst
        env:
          GITHUB_TOKEN: ${{ github.token }}
